services:
  sui-backend:
    image: ${REGISTRY}/sui-backend:latest
    build:
      context: ..
      dockerfile: backend/Dockerfile
    profiles:
      - backend
      - build
  sui-frontend:
    image: ${REGISTRY}/sui-frontend:latest
    build:
      context: ..
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: https://api.${HOST_NAME}
        VITE_WS_URL: wss://api.${HOST_NAME}
    profiles:
      - frontend
      - build