on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
      HOST_NAME: ${{ secrets.HOST_NAME }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image And Push
        run: | 
            docker compose -f .docker/compose.build.yaml --profile frontend build
            docker compose -f .docker/compose.build.yaml --profile frontend push

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
      HOST_NAME: ${{ secrets.HOST_NAME }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image And Push
        run: | 
            docker compose -f .docker/compose.build.yaml --profile backend build
            docker compose -f .docker/compose.build.yaml --profile backend push
  
  deploy:
    name: Deploy
    runs-on: sui-hackathon
    needs: [build-frontend, build-backend]
    env:
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_DB: ${{ secrets.PG_DB }}
      REGISTRY: ghcr.io/${{ github.repository }}
    steps:
    - name: Checkout Develop
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Clean Container, Image And Prepare For Deploy
      run: docker compose -f .docker/compose.yaml -p sui-hackathon --profile deploy down --rmi all -v
    - name: Deploy Application
      run: docker compose -f .docker/compose.yaml -p sui-hackathon --profile deploy up -d